name: TruffleHog Scan

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run TruffleHog Docker
      run: |
        docker run --rm -v $(pwd):/src -w /src trufflesecurity/trufflehog:latest filesystem /src --json > trufflehog-results.json

    - name: Upload TruffleHog results
      uses: actions/upload-artifact@v2
      with:
        name: trufflehog-results
        path: trufflehog-results.json

    - name: Display TruffleHog Results
      run: cat trufflehog-results.json
